server:
 port: 8088

spring:
 application:
  name: cloud-config
 cloud:
  config:
   server:
    git:
     uri: https://github.com/m1nuano/cloud-config
     default-label: master
     search-paths: "{application}"